/* istanbul ignore file */
const _irregularNouns = {
    "addendum": "addenda",
    "alga": "algae",
    "alumna": "alumnae",
    "apparatus": "apparatuses",
    "appendix": "appendices",
    "bacillus": "bacilli",
    "bacterium": "bacteria",
    "beau": "beaux",
    "belief": "beliefs",
    "bison": "bison",
    "bureau": "bureaus",
    "chef": "chefs",
    "child": "children",
    "chief": "chiefs",
    "corps": "corps",
    "corpus": "corpora",
    "curriculum": "curricula",
    "datum": "data",
    "deer": "deer",
    "die": "dice",
    "diagnosis": "diagnoses",
    "erratum": "errata",
    "fireman": "firemen",
    "fish": "fish",
    // "focus": "focuses",
    "foot": "feet",
    "genesis": "geneses",
    "genus": "genera",
    "goose": "geese",
    "halo": "halos",
    "index": "indices",
    "louse": "lice",
    "man": "men",
    "matrix": "matrices",
    "means": "means",
    "medium": "media",
    "memo": "memos",
    "memorandum": "memoranda",
    "moose": "moose",
    "mouse": "mice",
    "nebula": "nebulae",
    "ovum": "ova",
    "ox": "oxen",
    "person": "people",
    "photo": "photos",
    "piano": "pianos",
    "radius": "radii",
    "roof": "roofs",
    "series": "series",
    "sheep": "sheep",
    "scissors": "scissors",
    "species": "species",
    "stratum": "strata",
    "syllabus": "syllabi",
    "tableau": "tableaux",
    "that": "those",
    "this": "these",
    "tooth": "teeth",
    "vertebra": "vertebrae",
    "vita": "vitae",
    "woman": "women",
    "zero": "zeros"
};
export default _irregularNouns;




